### ISSUE TITLE
question about creating torque

### ISSUE THREAD

**Issue by Hayleymol** [Sohojoe/ActiveRagdollStyleTransfer#18]
Hello, thanks for the great repo to learn with.
I just came up with one question while reading your repo. 

I understood that you didn't use PD control like the original DeepMimic paper by reading the other question.
It seems like the learning agent's joint angle is directly targeted like;
muscle.TargetNormalizedRotationX = vectorAction[i++]

From what I understood, this only tells the rotation of the joint to follow.
My question is, how did you manage to create the torque to be applied to that joint?
I have seen UpdateMotor() function and wonder whether this is the related function?

**Comment by Sohojoe** [comment]
hi @Hayleymol - sorry I didn't see this before...

In this work, I do not use a PD controller. The motor is set in the [UpdateMotor()](https://github.com/Sohojoe/ActiveRagdollStyleTransfer/blob/79e5e4ea267e74125ec4d0d254009bebb733f298/UnitySDK/Assets/ActiveRagdollStyleTransfer/StyleTransfer002/Scripts/Muscle002.cs#L56) function. 

Internally, the joint figures out what force to apply in order to get to that target rotation speed.

In later work we switched to the ArticulationBody, which has a PD controller built-in (so one can specify the desired local angle per joint)

**Comment by Hayleymol** [comment]
Thank you for your answer! I will look into the switched ArticulationBody as well.
